server:
  port: 8072

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekas:8761/eureka/
      
spring:
  cloud:
    # loadbalancer.ribbon.enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowercaseserviceid: true
      default-filters: 
        - RemoveRequestHeader=Cookie, Set-Cookie
      routes:
        # - id: organizationservice
        #   uri: lb://organizationservice
        #   predicates:
        #     - Path=/organization/**
        #   filters:
        #     - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: licensingservice
          # uri: lb:licensingservice F
          uri: lb://licensingservice #unauthoried
          # uri: licensingservice format is incorrect, scheme can not be empty
          # uri: lb://license-service unavailable
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}
        
        
