server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  cloud:
    # loadbalancer.ribbon.enabled: false
    gateway:
      # discovery:
      #   locator:
      #     enabled: true
      #     lowerCaseServiceId: true
      default-filters: 
        - TokenRelay=
        - RemoveRequestHeader=Cookie, Set-Cookie
      routes:
        - id: organizationservice
          uri: lb://organizationservice
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: licensingservice
          uri: lb://licensingservice
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}
        
        
